Capstone.Web/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Capstone.Web.Models;
using Capstone.Web.DAL;
using System.IO;
using System.Web.Security;

namespace Capstone.Web.Controllers
{
    public class SearchController : CapstoneController
    {
        private readonly IPlanSqlDAL planDal;
        private readonly IRecipeSqlDAL recipeDal;
        private readonly IUserSqlDAL userDal;
        private readonly ISearchSqlDAL searchDal;

        public SearchController(IPlanSqlDAL planDal, IRecipeSqlDAL recipeDal, IUserSqlDAL userDal, ISearchSqlDAL searchDal) : base(userDal)
        {
            this.planDal = planDal;
            this.recipeDal = recipeDal;
            this.userDal = userDal;
            this.searchDal = searchDal;
        }

        
        // GET: Search
        public ActionResult Search()
        {
            SearchModel model = new SearchModel();
            List<string> cats = recipeDal.GetCategories();
            Dictionary<string, bool> catsDictionary = new Dictionary<string, bool>();
            foreach(string s in cats)
            {
                catsDictionary[s] = false;
            }
            model.SearchCategories = catsDictionary;
            return View(model);
        }
        [HttpPost]
        public ActionResult Search(SearchModel model)
        {
            model.RecipeHash = searchDal.GetSearchResults(model);

            List<string> cats = recipeDal.GetCategories();
            Dictionary<string, bool> catsDictionary = new Dictionary<string, bool>();
            foreach (string s in cats)
            {
                catsDictionary[s] = false;
            }
            model.SearchCategories = catsDictionary;

            

            return View(model);
        }
        public ActionResult SearchResults(HashSet<RecipeModel> recipes)
        {
            return View();
        }
    }
}

Capstone.Web/Controllers/UserController.cs
using Capstone.Web.DAL;
using Capstone.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Capstone.Web.Crypto;
using System.Web.Routing;
using log4net;



namespace Capstone.Web.Controllers
{
    public class UserController : CapstoneController
    {
        private readonly IPlanSqlDAL planDal;
        private readonly IRecipeSqlDAL recipeDal;
        private readonly IUserSqlDAL userDal;


        public UserController(IPlanSqlDAL planDal, IRecipeSqlDAL recipeDal, IUserSqlDAL userDal) : base(userDal)
        {
            this.planDal = planDal;
            this.recipeDal = recipeDal;
            this.userDal = userDal;
        }

        public ActionResult LogOut()
        {
            Session["authorizationlevel"] = null;
            Session["username"] = null;
            Session["user"] = null;
            return RedirectToAction("Index", "Home");
        }


        // GET: User
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        [Route("users/new")]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [Route("users/new")]
        public ActionResult Register(UserModel model)
        {
            if (!ModelState.IsValid)
            {

                return View("Register");
            }


            UserModel user = userDal.GetUser(model.UserName);

            if (user.UserName != null)
            {
                ModelState.AddModelError("username-exists", "That user name is not available");
                return View("Register", model);
            }
            else
            {
                HashProvider hash = new HashProvider();
                string password = hash.HashPassword(model.Password);
                model.Salt = hash.SaltValue;
                model.Password = password;
                model.AuthorizationLevel = 2;
                if(model.SignupBool == true)
                {
                    model.Signup = 1;
                }
                userDal.RegisterUser(model);

                FormsAuthentication.SetAuthCookie(user.Email, true);
                // Session[SessionKeys.Username] = model.EmailAddress;
                //Session[SessionKeys.UserId] = user.Id;  ??? whats session keys
            }

            return RedirectToAction("RegisterSuccess");
        }

        public ActionResult RegisterSuccess()
        {
            return View();
        }
        public ActionResult ChangePassword()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ChangePassword(ChangePasswordModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            UserModel user = Session["user"] as UserModel;
            HashProvider hash = new HashProvider();
            string s = model.TempPassword;
            s = hash.HashPassword(s);


            //if (!ModelState.IsValid)
            //{
            //    return View("ChangePassword");
            //}



            if (hash.VerifyPasswordMatch(user.Password, model.TempPassword, user.Salt) == false)
            {
                return View("ChangePassword");
            }

            else
            {
                
                string password = hash.HashPassword(model.Password);
                user.Salt = hash.SaltValue;
                model.Password = password;
                user.AuthorizationLevel = 2;
                userDal.ChangePassword(model.Password, user.Salt, user.UserName);

                //FormsAuthentication.SetAuthCookie(user.Email, true);
                // Session[SessionKeys.Username] = model.EmailAddress;
                //Session[SessionKeys.UserId] = user.Id;  ??? whats session keys
            }

            return RedirectToAction("ChangeSuccess");
        }

        public ActionResult ChangeSuccess()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View("Login");
        }

        [HttpPost]
        public ActionResult Login(LoginModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            //HashProvider hash = new HashProvider();
            //string password = hash.HashPassword(model.Password);
            //model.Password = model.Password;
            UserModel m = userDal.GetUser(model.UserName);
            if (ModelState.IsValid &&  m.Salt != null)
            {
                UserModel userLogin = userDal.GetUser(model.UserName);

                if (userLogin != null)
                {
                    HashProvider hashProvider = new HashProvider();
                    bool doesPasswordMatch = hashProvider.VerifyPasswordMatch(userLogin.Password, model.Password, userLogin.Salt);
                    if (!doesPasswordMatch)
                    {
                        ModelState.AddModelError("invalid-login", "The username or password combination is not valid");
                        return View("Login", model);
                    }
                    else
                    {
                        FormsAuthentication.SetAuthCookie(userLogin.UserName, true);
                        Session["authorizationlevel"] = userLogin.AuthorizationLevel;
                        Session["username"] = userLogin.UserName;
                        Session["user"] = userLogin;

                        return RedirectToAction("Index", "Home");
                    }
                }
                else
                {
                    ModelState.AddModelError("invalid-login", "The username or password combination is not valid");
                    return View("Login", model);
                }
                //return View("Login", model);
            }

            UserModel user = userDal.GetUser(model.UserName);

            return View("Login");
        }

        public ActionResult UserPage()
        {
            UserModel m = Session["user"] as UserModel;
            int userId = Convert.ToInt32(m.UserID);
            ViewBag.UserName = m.UserName;
            List<RecipeModel> model = recipeDal.GetUserRecipes(userId);
            return View(model);
        }


    }
}

Capstone.Web/Views/Shared/Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>


<head>
    <meta name="viewport" content="width=device-width" />
    <title>_Layout</title>

    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="~/Content/style.css" rel="stylesheet" />

</head>

<body class="bodyByBod">
    <header> 
            <a href="@Url.Action("Index","Home")"><img src="~/Img/Cancer-Support-Community.jpg" alt="Cancer Support Community Central Ohio" class="bodyByBod dingleberry"/></a>
        @*<a href="@Url.Action("Index", "Home")"><img src="~/Img/cancer-foundation-cancer-ribbons.jpg" alt="Support All Those Affected By Cancer" class="rightImage"/></a>*@


        </header>
    <br>
   
    <div> @*class="navbar navbar-inverse navbar-fixed-top"*@
        <div class="container, nav">
            <div>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("| Home |", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("| Register |", "Register", "User", new { area = "" }, new { @class = "navbar-brands" })
                @Html.ActionLink("| Login |", "Login", "User", new { area = "" }, new { @class = "navbar-brands" })
                @Html.ActionLink("| Search |", "Search", "Search", new { area = "" }, new { @class = "navbar-brand" })
                @if (Authorize.Registered((int?)Session["authorizationlevel"]) == true || Authorize.Admin((int?)Session["authorizationlevel"]) == true)
                {
                @Html.ActionLink("| Plan |", "Index", "Plan", new { area = "" }, new { @class = "navbar-brands" })
                }
                @using Capstone.Web.DAL@if (Authorize.Registered((int?)Session["authorizationlevel"]) == true || Authorize.Admin((int?)Session["authorizationlevel"]) == true)
                {
                @Html.ActionLink("| Add Recipe |", "AddRecipe", "Home", new { area = "" }, new { @class = "navbar-brands" })
                }
                @if (Authorize.Registered((int?)Session["authorizationlevel"]) == true || Authorize.Admin((int?)Session["authorizationlevel"]) == true)
                {
                    @Html.ActionLink("| Change Password |", "ChangePassword", "User", new { area = "" }, new { @class = "navbar-brands" })
                }
                @if (Authorize.Admin((int?)Session["authorizationlevel"]) == true)
                {
                @Html.ActionLink("| Admin |", "Admin", "Home", new { area = "" }, new { @class = "navbar-brands" })
                }
                @if (Authorize.Registered((int?)Session["authorizationlevel"]) == true || Authorize.Admin((int?)Session["authorizationlevel"]) == true)
                {
                    @Html.ActionLink("| User Page |", "UserPage", "User", new { area = "" }, new { @class = "navbar-brands" })
                }
                @if (Authorize.Registered((int?)Session["authorizationlevel"]) == true || Authorize.Admin((int?)Session["authorizationlevel"]) == true)
                {
                    @Html.ActionLink("| Logout |", "Logout", "User", new { area = "" }, new { @class = "navbar-brand" })
                }

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav, navbar-nav"></ul>
            </div>
        </div>
    </div>


    <div>
        @RenderBody()
    </div>
</body>
</html>

Capstone.Web/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>


<head>
    <meta name="viewport" content="width=device-width" />
    <title>_Layout</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Content/jquery.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script type="text/javascript" src="~/Content/masonry.pkgd.min.js"></script>
    <script type="text/javascript" src="~/Content/masonry-docs.min.js"></script>

    <link href="~/Content/style.css" rel="stylesheet" />
    <script src="~/Content/jquery.min.js"></script>
    <script src="~/Content/bootstrap.min.js"></script>
    <script>
        var main = function () {
            $('.dropdown-toggle').click(function () {
                $(this).parent().find('.dropdown-menu').toggle();
            });
        };
        $(document).ready(main);
    </script>

</head>

<body class="body">
    <header class="body"> 
            <a href="@Url.Action("Index","Home")"><img src="~/Img/Cancer-Support-Community.jpg" alt="Cancer Support Community Central Ohio" class="body dingleberry"/></a>
        </header>
    <br>   
    <div>
        <div class="container">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="@Url.Action("Index","Home")">Home</a>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="@Url.Action("Search","Search")">Search <span class="sr-only">(current)</span></a></li>
                            
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="@Url.Action("Login","User")">Login</a></li>
                                    <li><a href="@Url.Action("Register","User")">Register</a></li>
                                    @using Capstone.Web.DAL@if (Authorize.Registered((int?)Session["authorizationlevel"]) == true || Authorize.Admin((int?)Session["authorizationlevel"]) == true)
                                    {
                                    <li><a href="@Url.Action("Index","Plan")">Plan</a></li>
                                    }
                                    
                                    @using Capstone.Web.DAL@if (Authorize.Registered((int?)Session["authorizationlevel"]) == true || Authorize.Admin((int?)Session["authorizationlevel"]) == true)
                                    {
                                        <li><a href="@Url.Action("AddRecipe","Home")">Add Recipe</a></li>
                                    }                                    
                                    
                                    @using Capstone.Web.DAL@if (Authorize.Registered((int?)Session["authorizationlevel"]) == true || Authorize.Admin((int?)Session["authorizationlevel"]) == true)
                                    {
                                        <li><a href="@Url.Action("UserPage","User")">User Page</a></li>
                                    }
                                    @using Capstone.Web.DAL@if (Authorize.Registered((int?)Session["authorizationlevel"]) == true || Authorize.Admin((int?)Session["authorizationlevel"]) == true)
                                    {
                                        <li><a href="@Url.Action("ChangePassword","User")">Change Password</a></li>
                                    }
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            @using Capstone.Web.DAL@if (Authorize.Admin((int?)Session["authorizationlevel"]) == true)
                            {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="@Url.Action("Admin","Home")">Admin</a></li>
                                    <li><a href="@Url.Action("Index","Plan")">Plan</a></li>
                                    <li><a href="@Url.Action("AddRecipe","Home")">Add Recipe</a></li>
                                    <li><a href="@Url.Action("UserPage","User")">User Page</a></li>
                                    <li><a href="@Url.Action("ChangePassword","User")">Change Password</a></li>
                                </ul>
                            </li>
                            }
                            @if (Authorize.Registered((int?)Session["authorizationlevel"]) == true || Authorize.Admin((int?)Session["authorizationlevel"]) == true)
                            {
                                <li><a href="@Url.Action("Logout", "User")">Logout</a></li>
                            }
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>
            </div>
            </div>


    <div>
        @RenderBody()
    </div>
</body>
</html>